import { createClient } from '@supabase/supabase-js'
import { NextResponse } from 'next/server'
import { noraGenerate } from '@/lib/nora'

export async function POST(request) {
  try {
    const { sessionId, coupleId, roundNumber = 1 } = await request.json()
    if (!sessionId || !coupleId) {
      return NextResponse.json({ error: 'sessionId and coupleId required' }, { status: 400 })
    }

    const supabase = createClient(
      process.env.NEXT_PUBLIC_SUPABASE_URL,
      process.env.SUPABASE_SERVICE_ROLE_KEY
    )

    // Get session
    const { data: session } = await supabase
      .from('game_sessions')
      .select('*')
      .eq('id', sessionId)
      .maybeSingle()
    if (!session) return NextResponse.json({ error: 'Session not found' }, { status: 404 })

    // Check if this round already exists — idempotent
    const { data: existingRound } = await supabase
      .from('game_rounds')
      .select('*')
      .eq('session_id', sessionId)
      .eq('round_number', roundNumber)
      .maybeSingle()

    if (existingRound) {
      // Return existing round data — don't generate twice
      return NextResponse.json({
        topic: session.hole_topic,
        entry: session.hole_entry,
        nora_send_off: session.nora_send_off,
        thread_user1: existingRound.user1_thread,
        thread_user2: existingRound.user2_thread,
        round: roundNumber,
        alreadyExists: true,
      })
    }

    const isFirstRound = roundNumber === 1

    // For round 1, check if topic was already generated by the other user
    if (isFirstRound && session.hole_topic) {
      const { data: existingRound } = await supabase
        .from('game_rounds')
        .select('*')
        .eq('session_id', sessionId)
        .eq('round_number', 1)
        .maybeSingle()

      if (existingRound) {
        return NextResponse.json({
          topic: session.hole_topic,
          entry: session.hole_entry,
          nora_send_off: session.nora_send_off,
          thread_user1: existingRound.user1_thread,
          thread_user2: existingRound.user2_thread,
          round: 1,
          alreadyExists: true,
        })
      }
    }

    // Get couple
    const { data: couple } = await supabase
      .from('couples')
      .select('user1_id, user2_id')
      .eq('id', coupleId)
      .maybeSingle()
    if (!couple) return NextResponse.json({ error: 'Couple not found' }, { status: 404 })

    // Get both partners' interests and names
    const [{ data: user1Profile }, { data: user2Profile }] = await Promise.all([
      supabase.from('user_profiles').select('display_name, game_interests').eq('user_id', couple.user1_id).maybeSingle(),
      supabase.from('user_profiles').select('display_name, game_interests').eq('user_id', couple.user2_id).maybeSingle(),
    ])

    const user1Name = user1Profile?.display_name || 'Partner 1'
    const user2Name = user2Profile?.display_name || 'Partner 2'

    // Get previous rounds for context
    const { data: previousRounds } = await supabase
      .from('game_rounds')
      .select('*')
      .eq('session_id', sessionId)
      .order('round_number', { ascending: true })

    // Get all finds so far for context
    const { data: allFinds } = await supabase
      .from('game_finds')
      .select('*')
      .eq('session_id', sessionId)
      .order('created_at', { ascending: true })

    const user1Finds = allFinds?.filter(f => f.user_id === couple.user1_id) || []
    const user2Finds = allFinds?.filter(f => f.user_id === couple.user2_id) || []

    const timerMinutes = session.timer_minutes || 60

    // Build context for subsequent rounds
    const previousContext = previousRounds?.length > 0 ? `
Previous rounds context:
${previousRounds.map(r => `Round ${r.round_number}: ${user1Name} had thread: "${r.user1_thread}" / ${user2Name} had thread: "${r.user2_thread}"`).join('\n')}

What they found so far:
${user1Name}: ${user1Finds.map(f => f.find_text).join(' | ') || 'Nothing yet'}
${user2Name}: ${user2Finds.map(f => f.find_text).join(' | ') || 'Nothing yet'}
`.trim() : ''

    const user1Interests = user1Profile?.game_interests || {}
    const user2Interests = user2Profile?.game_interests || {}

    const sharedTopics = [
      ...(user1Interests.topics || []),
      ...(user1Interests.obsessions || []),
    ].filter(t =>
      (user2Interests.topics || []).concat(user2Interests.obsessions || []).some(t2 =>
        t2.toLowerCase().includes(t.toLowerCase()) || t.toLowerCase().includes(t2.toLowerCase())
      )
    )

    const interestsContext = `
${user1Name}'s interests: ${JSON.stringify(user1Interests)}
${user2Name}'s interests: ${JSON.stringify(user2Interests)}
Shared or overlapping interests: ${sharedTopics.length > 0 ? sharedTopics.join(', ') : 'Not explicitly identified — use judgment'}
`.trim()

    let prompt

    if (isFirstRound) {
      prompt = `You are Nora — warm, witty, mischievous game master. You are generating Round 1 of a Rabbit Hole game for a couple.

Here is what you know about them:
${interestsContext}

Their game timer is ${timerMinutes} minutes.

Your job is to pick ONE specific topic — a real case, event, person, or mystery — and give both players different angles into the SAME story. They will share what they find throughout the game and you will bring it all together at the end.

CRITICAL RULES:
- Both players must be investigating the SAME topic/case/person/event — not different stories
- Round 1 threads must be SPECIFIC and LOW HANGING FRUIT — easy to find information about, a direct unambiguous starting task
- Name the specific person, case, place, or event explicitly in each thread
- ${user1Name}'s thread and ${user2Name}'s thread must approach the SAME topic from different angles
- The entry point must be ONE irresistible sentence that makes both of them go "wait, tell me more"
- TOPIC SELECTION PRIORITY: (1) Pick from shared/overlapping interests first — true crime, history, documentaries, or anything both profiles touch. (2) If no clear overlap, pick a topic where both players have a natural angle even if it's not explicitly listed. (3) Occasionally surprise them with a wild card topic Nora thinks they'd love — but this should be the exception, not the rule.
- Never pick a topic that only one person would care about
- The best topics have a human mystery or surprising truth at the center
- You already know how this story ends — you are the host who picked it

Respond ONLY with JSON, no markdown:
{
  "topic": "2-4 word topic name",
  "entry": "One irresistible sentence that drops both players into the same story — specific, names a real person/case/event",
  "nora_send_off": "One punchy Nora line — witty, warm, slightly mischievous — that sends them off",
  "thread_user1": "Specific task for ${user1Name} — names the exact person/case, asks them to find one specific thing. Start with 'Find out...' or 'Discover...'",
  "thread_user2": "Specific task for ${user2Name} — same topic, different angle. Names the exact person/case, asks them to find a different specific thing. Start with 'Find out...' or 'Discover...'",
  "factual_close": "What actually happened — the real ending to this story. 2-3 sentences. Facts only.",
  "human_truth": "The deeper human truth this story reveals. 2-3 sentences. This is Nora's philosophical layer on top of the facts.",
  "topic_media": "A book, podcast, documentary, or film directly about this topic if one exists — or null"
}`
    } else {
      prompt = `You are Nora — warm, witty, mischievous game master. A couple is playing the Rabbit Hole game. They are now on Round ${roundNumber}.

Topic: ${session.hole_topic}
Original entry: ${session.hole_entry}

${previousContext}

Your job is to send them DEEPER into the same topic with new angles. Round ${roundNumber} threads should go deeper than the previous rounds — more specific, more surprising, digging into something they haven't found yet.

CRITICAL RULES:
- Still the SAME topic — go deeper, not sideways into a different story
- Reference what they already found if possible — build on their actual discoveries
- Each new thread should reveal a new surprising angle of the same story
- Push them toward the convergence — they're getting closer to the full picture

Respond ONLY with JSON, no markdown:
{
  "thread_user1": "New deeper task for ${user1Name} — builds on what they found, goes further into the same story",
  "thread_user2": "New deeper task for ${user2Name} — builds on what they found, goes further from a different angle",
  "nora_nudge": "One short Nora line (1 sentence) to send them back in — references something they found, builds excitement"
}`
    }

    const response = await noraGenerate(prompt, { route: 'game-room/generate-hole', maxTokens: 800 })

    const raw = response
    const cleaned = raw.replace(/^```(?:json)?\n?/, '').replace(/\n?```$/, '').trim()
    let generated
    try {
      generated = JSON.parse(cleaned)
    } catch (err) {
      console.error('[generate-hole] Parse error:', err, raw)
      return NextResponse.json({ error: 'Failed to parse response' }, { status: 500 })
    }

    // For round 1 — save topic/entry/close/truth to session
    if (isFirstRound) {
      await supabase
        .from('game_sessions')
        .update({
          hole_topic: generated.topic,
          hole_entry: generated.entry,
          nora_send_off: generated.nora_send_off,
          convergence: generated.human_truth,
          factual_close: generated.factual_close,
          topic_media: generated.topic_media || null,
          updated_at: new Date().toISOString(),
        })
        .eq('id', sessionId)
    }

    // Save round to game_rounds
    await supabase
      .from('game_rounds')
      .insert({
        session_id: sessionId,
        couple_id: coupleId,
        round_number: roundNumber,
        user1_thread: generated.thread_user1,
        user2_thread: generated.thread_user2,
        status: 'active',
      })

    // Always return from DB — never return locally generated content
    // This ensures both users get identical content even if they raced to generate
    const { data: savedRound } = await supabase
      .from('game_rounds')
      .select('*')
      .eq('session_id', sessionId)
      .eq('round_number', roundNumber)
      .maybeSingle()

    const { data: updatedSession } = await supabase
      .from('game_sessions')
      .select('hole_topic, hole_entry, nora_send_off, factual_close, convergence, topic_media')
      .eq('id', sessionId)
      .maybeSingle()

    return NextResponse.json({
      topic: updatedSession?.hole_topic,
      entry: updatedSession?.hole_entry,
      nora_send_off: isFirstRound ? updatedSession?.nora_send_off : null,
      nora_nudge: !isFirstRound ? generated.nora_nudge : null,
      thread_user1: savedRound?.user1_thread,
      thread_user2: savedRound?.user2_thread,
      factual_close: isFirstRound ? updatedSession?.factual_close : null,
      human_truth: isFirstRound ? updatedSession?.convergence : null,
      topic_media: isFirstRound ? updatedSession?.topic_media : null,
      round: roundNumber,
    })

  } catch (err) {
    console.error('[generate-hole] Error:', err)
    return NextResponse.json({ error: 'Internal server error' }, { status: 500 })
  }
}
