// ── SENSITIVE-CONTENT SAFETY GATE ───────────────────────────────────────────
// Added task #187, Aug 11 2026. Both app/api/ai-coach/route.js and
// app/api/couples-session/route.js already had an in-prompt "CRISIS
// DETECTION" instruction (hotline numbers), but neither did anything
// pre-generation — a crisis disclosure went straight to noraChat, and
// updateNoraMemory() fired unconditionally afterward regardless of what the
// turn contained. This module is the deterministic gate that was missing.
//
// Deliberately narrow: one cheap classifier call, four categories that
// mirror the product's own existing CRISIS DETECTION language (abuse /
// self-harm / suicidal ideation / a broader active crisis) — not a
// general-purpose intent classifier, per explicit scope instruction.

import { noraSignal } from './nora.js'

// Fixed, human-reviewed response. Never generated by the model — its
// wording must never be shaped by the disclosure that triggered it, and it
// must never vary. Update this copy with care; it is the entire safety
// surface shown when the gate fires.
export const SAFETY_RESPONSE = `I hear you, and I want to take what you just shared seriously. This isn't something I'm the right kind of help for — please reach out to people who are equipped for this:

National Domestic Violence Hotline: 1-800-799-7233
Crisis Text Line: text HOME to 741741
988 Suicide & Crisis Lifeline: call or text 988

If you're in immediate danger, please call 911. I'm here whenever you want to keep talking about anything else.`

// checkSensitiveContent(text) -> { flagged, category, ok }
//
// ok:false means the classifier itself failed, timed out, or returned
// something unusable — this is NOT the same thing as "not flagged," and
// callers must not treat it as such for anything touching memory. See the
// design note in ai-coach/route.js and couples-session/route.js for the
// fail-open (generation) / fail-closed (memory) reasoning behind that
// distinction — it is a deliberate decision for this specific call, not a
// copy of shouldUpdateMemory()'s existing fail-toward-false convention in
// lib/nora-memory.js, because the stakes of getting it wrong are different:
// shouldUpdateMemory failing quietly just means a conversation isn't
// remembered; this gate failing quietly (if treated as "safe") could mean a
// crisis disclosure gets ordinary treatment.
export async function checkSensitiveContent(text) {
  if (!text || !text.trim()) return { flagged: false, category: null, ok: true }

  try {
    const prompt = `You are a safety classifier for a relationship-coaching app. Decide whether this message contains a genuine disclosure of abuse, self-harm, suicidal ideation, or an active personal crisis.

Be sensitive to real disclosures. Do NOT flag ordinary relationship frustration, venting about a partner, or hyperbole ("this is killing me," "I could scream").

Message: "${text}"

Respond with EXACTLY one word, nothing else:
NONE
ABUSE
SELF_HARM
SUICIDAL_IDEATION
CRISIS`

    const result = await noraSignal(prompt, {
      route: 'safety/check-sensitive-content',
      maxTokens: 10,
    })

    const category = result.trim().toUpperCase().split(/\s+/)[0]

    if (category === 'NONE') return { flagged: false, category: null, ok: true }
    if (['ABUSE', 'SELF_HARM', 'SUICIDAL_IDEATION', 'CRISIS'].includes(category)) {
      return { flagged: true, category, ok: true }
    }

    // Classifier ran but returned something we don't recognize — treat as
    // a failure, not as "safe." See ok:false contract above.
    return { flagged: false, category: null, ok: false }
  } catch {
    return { flagged: false, category: null, ok: false }
  }
}

// resolveSafetyAction(safety) -> 'SAFETY_RESPONSE_ONLY' | 'GENERATE_ONLY' | 'GENERATE_AND_REMEMBER'
//
// The single decision both app/api/ai-coach/route.js and
// app/api/couples-session/route.js branch on, extracted so it's one
// canonical place instead of two near-identical if/else blocks that could
// drift out of sync. Pure function — trivially unit-testable (see
// tests/safety-gate-decision.test.js) without needing to exercise the
// actual Next.js route handlers.
//
//   flagged            -> SAFETY_RESPONSE_ONLY: skip noraChat entirely,
//                          return the fixed SAFETY_RESPONSE, never touch
//                          updateNoraMemory.
//   !flagged && !ok     -> GENERATE_ONLY: the classifier itself failed, so
//                          we don't know if this was safe. Fail-open on
//                          generation (Nora still responds normally — a
//                          transient classifier hiccup shouldn't make Nora
//                          unusable) but fail-closed on memory (skip
//                          updateNoraMemory — a turn the classifier
//                          couldn't evaluate must never enter notes/claims
//                          "by default").
//   !flagged && ok      -> GENERATE_AND_REMEMBER: the ordinary path,
//                          unchanged from before this gate existed.
export function resolveSafetyAction(safety) {
  if (safety.flagged) return 'SAFETY_RESPONSE_ONLY'
  if (!safety.ok) return 'GENERATE_ONLY'
  return 'GENERATE_AND_REMEMBER'
}
